variable "region" {}
variable "dev_vpc_cidr" {}
variable "public_subnets" {}
variable "private_subnets" {}
variable "app_name" {}
variable "app_env" {}
variable "dev_image_tag" {}
variable "caller_id" {}
variable "dev_ecr_url" {}