name: Destroy infrastructure
on:
  workflow_dispatch:

jobs:

  destroy:
    name: "Destroy AWS"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'

    - name: Install Terraform
      uses: little-core-labs/install-terraform@v2.0.0
      with:
        version: 1.2.6
    
    - name: Terraform prepare
      working-directory: ./TerraformASGL
      run:
        set -e
        export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        export AWS_REGION="us-east-1"

    - name: Terraform apply
      working-directory: ./TerraformASGL
      run: |
        terraform init -reconfigure -upgrade
        terraform fmt
        terraform validate
        terraform plan
        terraform apply -auto-approve

    - name: Show Destroy plan
      run: terraform plan -destroy
      continue-on-error: true

    - name: Destroy resources jobs
      id: destroy
      run: terraform destroy -auto-approve -var-file=terraform.tfvars

    - name: Delete plan file
      if: steps.destroy.outcome == 'success'
      run: aws s3 rm s3://glas-backend-bucket/production/terraform.tfstate
      env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: ${{ secrets.REGION }}