name: CI Testing and building test image

on:
  push:
  pull_request:

jobs:

  Terraform_Unit_Check:
    name: 3- Basic terraform configuration actions/checkout
    #needs: [Unit_tests, Build]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install local terraform
      uses: little-core-labs/install-terraform@v2.0.0
      with:
        version: 1.2.6

    - name: Terraform fmt and validate
      working-directory: ./Terraform_INIT
      run: |
        terraform init -backend=false
        terraform fmt
        terraform fmt -check
        terraform validate

  Unit_tests:
    name: 1- Unit tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Perform unit tests on code
      run: echo ------------------PLEASE PUT TESTS HERE------------------------------

  Build:
    name: 2- Test build docker image
    needs: Unit_tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Test - Build the Docker image
      working-directory: ./Docker
      run: docker build .

