name: CI dev pipeline

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run File and collect logs
        id: run
        working-directory: ./Docker/Sources
        run:  |
          export FILE_NAME=$(ls *.py)
          echo Running File...
          status=$(python $FILE_NAME > log.txt 2>&1; echo $?)
          cat log.txt
          echo ::set-output name=status::$status
      - name: Commit log
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add -A
          git checkout master
          git diff-index --quiet HEAD || git commit -am "deploy workflow logs"
          git push
      - name: Check run status
        if: steps.run.outputs.status != '0'
        run: exit "${{ steps.run.outputs.status }}

      - name: Build image with spider project
        working-directory: ./Docker
        env:
          ECR_REGISTRY: ${{steps.login-ecr.outputs.registry}}
          ECR_REPOSITORY: dev_image_repository
          IMAGE_TAG: DEV_SCRAPY_IMAGE

        run: |
          docker build .
       