name: CI Testing and building test image

on:
  push:
  pull_request:

jobs:
  Unit_tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Perform unit tests on code
      run: echo ------------------PLEASE PUT TESTS HERE------------------------------

  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Test - Build the Docker image
      working-directory: ./Docker
      run: docker build .

       