name: CI Testing and building test image

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Perform unit tests on code
    - name: Test - Build the Docker image
      working-directory: ./Docker
      run: docker build .

       