name: CI Testing and building test image

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Test - Build the Docker image
      working-directory: ./Docker
      run: docker build .

       